"use client";
import { useMemo, useState } from "react";
import { Search, ArrowUpRight, Info, Download, ChevronRight } from "lucide-react";

const lines=[
 ["Educação em Ciências e Matemática","ECM",10],["Educação Escolar: Teorias e Práticas Críticas","EETPC",12],["Educação, Cultura e Subjetividade","ECS",11],["Estado, Política e Formação Humana","EPFH",10],["Formação de Professores e Outros Agentes Educacionais","FPOAE",9],["História, Filosofia e Sociologia da Educação","HFSE",9],["Práticas Sociais e Processos Educativos","PSPE",6],["Relações étnico-raciais, diversidade e educação","RED",7]
] as const;
const people=[
 ["Ademir Donizete Caldeira","ECM"],["Alice H. C. Pierson","ECM"],["Cármen L. B. Passos","ECM"],["Carolina Rodrigues de Souza","ECM"],["Denise de Freitas","ECM"],["Denise Silva Vilela","ECM"],["Ettore Paredes Antunes","ECM"],["Maria do Carmo de Sousa","ECM"],["Mariana dos Santos","ECM"],["Michel Pisa Carnio","ECM"],
 ["Aline Sommerhalder","EETPC"],["Celso Luiz Aparecido Conti","EETPC"],["Emília Freitas de Lima","EETPC"],["Fabiana Marini Braga","EETPC"],["Fernando Donizete Alves","EETPC"],["Fernando Stanzione Galizia","EETPC"],["Jarina Rodrigues Fernandes","EETPC"],["Lorenzo Manera","EETPC"],["Luana Costa Almeida","EETPC"],["Maria Aparecida Mello","EETPC"],["Renata Maria Moschen Nascente","EETPC"],["Roseli Rodrigues de Mello","EETPC"],
 ["Alessandra Arce Hai","ECS"],["Antônio Álvaro Soares Zuin","ECS"],["Braian Garrito Veloso","ECS"],["Daniel Ribeiro Silva Mill","ECS"],["Flávio Caetano da Silva","ECS"],["Luiz Roberto Gomes","ECS"],["Maria Cecília Luiz","ECS"],["Maria Iolanda Monteiro","ECS"],["Michele Varotto Machado","ECS"],["Nilson Fernandes Dinis","ECS"],["Sandra Aparecida Riscal","ECS"],
 ["Débora Cristina Fonseca","EPFH"],["Eduardo Pinto e Silva","EPFH"],["Elenice Maria Cammarosano Onofre","EPFH"],["Géssica Priscila Ramos","EPFH"],["João dos Reis Silva Júnior","EPFH"],["Joelson Gonçalves de Carvalho","EPFH"],["José Carlos Rothen","EPFH"],["Luiz Bezerra Neto","EPFH"],["Maria Cristina da Silveira G. Fernandes","EPFH"],["Priscila Carla Cardoso","EPFH"],
 ["Adriana Fernandes Coimbra Marigo","FPOAE"],["Alexandre Rodrigo Nishiwaki da Silva","FPOAE"],["Aline M. de M. R. Reali","FPOAE"],["Ana Paula Gestoso de Souza","FPOAE"],["Cleonice Maria Tomazzetti","FPOAE"],["Dijnane Fernanda Vedovatto Machado","FPOAE"],["Klinger Teodoro Ciríaco","FPOAE"],["Márcia Regina Onofre","FPOAE"],["Rosa Maria Moraes Anunciato","FPOAE"],
 ["Carlos Roberto Massao Hayashi","HFSE"],["Denise Maria Reis","HFSE"],["Luís Antonio Groppo","HFSE"],["Maria Cristina Piumbato Innocentini Hayashi","HFSE"],["Marisa Bittar","HFSE"],["Paolo Nosella","HFSE"],["Poliana Bruno Zuin","HFSE"],["Roseli Esquerdo Lopes","HFSE"],["Vagno Emygdio Machado Dias","HFSE"],
 ["Aline Guerra Aquilante","PSPE"],["Denise Aparecida Correa","PSPE"],["Iraí Maria de Campos Teixeira","PSPE"],["Luiz Gonçalves Junior","PSPE"],["Natália Rejane Salim","PSPE"],["Osmar Moreira de Souza Junior","PSPE"],
 ["Alan Victor Pimenta de Almeida Pales Costa","RED"],["Ana Cristina Juvenal da Cruz","RED"],["Andrea Braga Moruzzi","RED"],["Douglas Verrângia Correa da Silva","RED"],["Maria Cristina dos Santos","RED"],["Manoel Nelito M. Nascimento","RED"],["Tatiane Cosentino Rodrigues","RED"]
] as const;
const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();

export default function Home(){
 const [tab,setTab]=useState("Visão geral"); const [q,setQ]=useState(""); const [selected,setSelected]=useState("Todas");
 const filtered=useMemo(()=>people.filter(p=>(selected==="Todas"||p[1]===selected)&&norm(p[0]).includes(norm(q))),[q,selected]);
 return <main>
  <header><a className="identity" href="#"><span>PPGE</span><div><b>Produção científica</b><small>Universidade Federal de São Carlos</small></div></a><nav>{["Visão geral","Linhas","Docentes","Método"].map(x=><button className={tab===x?"on":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><a className="institution" href="https://www.ppge.ufscar.br/pt-br" target="_blank">ppge.ufscar.br <ArrowUpRight size={13}/></a></header>

  <section className="masthead"><div><p>OBSERVATÓRIO DO PROGRAMA</p><h1>Produção científica<br/>do PPGE/UFSCar</h1></div><div className="mast-note"><span className="status-dot"/> Base em preparação<div>ORCID + OpenAlex<br/><small>Artigos de periódicos validados</small></div></div></section>

  {tab==="Visão geral"&&<section className="dashboard">
   <div className="section-title"><div><span>01</span><h2>Panorama</h2></div><p>Os totais bibliográficos serão publicados após a validação dos identificadores e do gênero documental.</p></div>
   <div className="kpis"><article><small>Docentes mapeados</small><strong>74</strong><p>distribuídos em oito linhas</p></article><article className="pending"><small>Artigos validados</small><strong>—</strong><p>coleta ainda não consolidada</p></article><article className="pending"><small>Periódicos distintos</small><strong>—</strong><p>fontes editoriais em validação</p></article><article className="pending"><small>Artigos em coautoria</small><strong>—</strong><p>indicador será calculado no corpus</p></article></div>
   <div className="data-grid"><article className="chart"><div className="panel-head"><div><small>COMPOSIÇÃO DO PROGRAMA</small><h3>Docentes por linha de pesquisa</h3></div><span>n = 74</span></div><div className="bars">{lines.map(l=><div key={l[1]}><label><b>{l[1]}</b><span>{l[2]}</span></label><i><em style={{width:`${l[2]/12*100}%`}}/></i></div>)}</div></article><article className="empty-panel"><div className="panel-head"><div><small>SÉRIE HISTÓRICA</small><h3>Artigos por ano</h3></div></div><div className="await"><span>Dados em processamento</span><p>O gráfico será exibido quando os artigos forem deduplicados por DOI e OpenAlex Work ID.</p></div><div className="axis"><span>2000</span><span>2010</span><span>2020</span><span>2026</span></div></article></div>
   <div className="criteria"><Info size={18}/><div><b>O que entra no painel?</b><p>Somente artigos vinculados a um periódico identificado. Livros, capítulos, e-books, anais e repositórios são excluídos, mesmo quando aparecem como “article” na fonte original.</p></div><button onClick={()=>setTab("Método")}>Ver critérios <ChevronRight size={14}/></button></div>
  </section>}

  {tab==="Linhas"&&<section className="content"><div className="section-title"><div><span>02</span><h2>Linhas de pesquisa</h2></div><p>Estrutura institucional usada para agrupar docentes e comparar a produção.</p></div><div className="line-list">{lines.map((l,i)=><article key={l[1]}><span>{String(i+1).padStart(2,"0")}</span><div><b>{l[0]}</b><small>{l[1]}</small></div><strong>{l[2]} <small>docentes</small></strong></article>)}</div></section>}

  {tab==="Docentes"&&<section className="content"><div className="section-title"><div><span>03</span><h2>Docentes</h2></div><p>O ORCID iD será a chave principal para resolver variações de autoria.</p></div><div className="filters"><label><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nome"/></label><select value={selected} onChange={e=>setSelected(e.target.value)}><option>Todas</option>{lines.map(l=><option key={l[1]} value={l[1]}>{l[1]} — {l[0]}</option>)}</select></div><div className="faculty-table"><div className="table-head"><span>Docente</span><span>Linha</span><span>Identificadores</span></div>{filtered.map(p=><div className="row" key={p[0]}><b>{p[0]}</b><span>{p[1]}</span><small>validação pendente</small></div>)}</div></section>}

  {tab==="Método"&&<section className="content"><div className="section-title"><div><span>04</span><h2>Critérios e procedência</h2></div><p>Uma base pequena, verificável e reproduzível é mais útil do que um conjunto amplo com documentos classificados incorretamente.</p></div><div className="method-grid"><article><span>1</span><h3>Resolver autoria</h3><p>Nome institucional → ORCID iD → OpenAlex Author ID. Nomes nunca serão a chave exclusiva.</p></article><article><span>2</span><h3>Selecionar artigos</h3><p>Tipo artigo, periódico identificado e autoria persistente são requisitos cumulativos.</p></article><article><span>3</span><h3>Validar a fonte</h3><p>OpenAlex Source ID, ISSN e nome do periódico permitem excluir e-books, capítulos e repositórios.</p></article><article><span>4</span><h3>Deduplicar</h3><p>DOI é a chave preferencial; OpenAlex Work ID sustenta registros sem DOI. Conflitos seguem para revisão.</p></article></div><div className="download-note"><div><Download size={19}/><span><b>Dados abertos</b><small>CSV, JSON e documentação dos critérios serão disponibilizados com a primeira versão validada.</small></span></div><em>Em preparação</em></div></section>}
  <footer><span>PPGE / UFSCar</span><p>Desenvolvido por <a href="https://orcid.org/0000-0002-9996-9983" target="_blank" rel="noreferrer">Gerlan Silva da Silva</a><br/><em>Doutorando em Educação pela UFSCar</em></p><small>ORCID + OpenAlex · atualização e critérios documentados</small></footer>
 </main>
}
